<?php

namespace SNT\immobilierBundle\Repository;

/**
 * RoleEntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleEntiteRepository extends \Doctrine\ORM\EntityRepository
{
}
