<?php

namespace SNT\immobilierBundle\Repository;

/**
 * UtilisateurEntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurEntiteRepository extends \Doctrine\ORM\EntityRepository
{
}
